name: Question
description: If you have a question about the macro, please open it here.
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ **Important: Please Read Before Submitting**

        **Do NOT open issues related to RDP or non-macro-related problems.**  
        Such issues will be **closed immediately**.

  - type: checkboxes
    attributes:
      label: Already reported? *
      description: Before asking, check if your question has already been answered in the open or closed issues.
      options:
      - label: I have searched the existing open and closed issues.
        required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: "Describe your question about the macro."
    validations:
      required: true
